### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by ubuntu204** [shoghilin/license_plate_recognition_with_yolov7#1]
Hello @shoghilin 
When running the training command in the last line of the setup.sh script, I received the following error:

```
train: New cache created: Dataset/train/labels.cache
Traceback (most recent call last):
  File "train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 245, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/ubuntu/Desktop/github/6.license_plate_recognition_with_yolov7/yolov7/utils/datasets.py", line 69, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/ubuntu/Desktop/github/6.license_plate_recognition_with_yolov7/yolov7/utils/datasets.py", line 408, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)

```

**Comment by shoghilin** [comment]
I think it is a dataset issue.
Can you check dataset has been processed successfully or not?

I rebuilt the project, and it ran perfectly fine.
Please make sure you have downloaded the dataset to the root of this project, and name the folder "car-plate-detection".
PS, I updated README.md in case it is not clear enough.
